// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.865
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Base() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\"><title>goth stack</title><link rel=\"stylesheet\" href=\"/static/output.css\"><link href=\"https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css\" rel=\"stylesheet\"><script src=\"https://unpkg.com/htmx.org@1.9.5\"></script><link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/franken-ui@2.1.0-next.6/dist/css/core.min.css\"><script src=\"https://cdn.jsdelivr.net/npm/franken-ui@2.1.0-next.6/dist/js/core.iife.js\"></script><link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/franken-ui@2.1.0-next.6/dist/css/utilities.min.css\"><script src=\"https://cdn.jsdelivr.net/npm/franken-ui@2.1.0-next.6/dist/js/icon.iife.js\"></script><script src=\"https://cdn.jsdelivr.net/npm/franken-ui@2.1.0-next.6/dist/js/chart.iife.js\"></script><script>\n  const htmlElement = document.documentElement;\n\n  const __FRANKEN__ = JSON.parse(localStorage.getItem(\"__FRANKEN__\") || \"{}\");\n\n  if (\n    __FRANKEN__.mode === \"dark\" ||\n    (!__FRANKEN__.mode &&\n      window.matchMedia(\"(prefers-color-scheme: dark)\").matches)\n  ) {\n    htmlElement.classList.add(\"dark\");\n  } else {\n    htmlElement.classList.remove(\"dark\");\n  }\n\n  htmlElement.classList.add(__FRANKEN__.theme || \"uk-theme-zinc\");\n  htmlElement.classList.add(__FRANKEN__.radii || \"uk-radii-md\");\n  htmlElement.classList.add(__FRANKEN__.shadows || \"uk-shadows-sm\");\n  htmlElement.classList.add(__FRANKEN__.font || \"uk-font-sm\");\n  htmlElement.classList.add(__FRANKEN__.chart || \"uk-chart-default\");\n</script></head><body class=\"bg-background text-foreground\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
